version: '2'

networks:
  kafka_wz_network:
    name: kafka_wz_network

services:
  kafka_wz_node_1:
    image: confluentinc/cp-kafka:latest
    container_name: kafka_wz_node_1
    networks: 
      - kafka_wz_network
    ports:
      - 29095:29095
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_LISTENERS: INTERNAL://kafka_wz_node_1:9092,CONTROLLER://kafka_wz_node_1:29093,EXTERNAL://kafka_wz_node_1:29095
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka_wz_node_1:9092,EXTERNAL://localhost:29095
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka_wz_node_1:29093,2@kafka_wz_node_2:29093
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      CLUSTER_ID: Xj90hkMKMjRPKqgHy9P6hg== # A unique 16-byte base64 UUID for the cluster. Can be generated online, or with or with bin/kafka-storage.sh random-uuid.
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      
  kafka_wz_node_2:
    image: confluentinc/cp-kafka:latest
    container_name: kafka_wz_node_2
    networks: 
      - kafka_wz_network
    ports:
      - 29096:29096
    environment:
      KAFKA_NODE_ID: 2
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_LISTENERS: INTERNAL://kafka_wz_node_2:9092,CONTROLLER://kafka_wz_node_2:29093,EXTERNAL://kafka_wz_node_2:29096
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka_wz_node_2:9092,EXTERNAL://localhost:29096
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka_wz_node_1:29093,2@kafka_wz_node_2:29093
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      CLUSTER_ID: Xj90hkMKMjRPKqgHy9P6hg==
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
